-- ============================================================================
-- Migration 053: Workflow Registry
-- Adapted for: TotalGuard Yard Care (TotalGuard LLC)
-- Creates a registry of all N8N workflows with their configuration requirements,
-- status tracking, and dependency mapping.
-- CRM: Jobber (replacing HouseCall Pro / HCP)
-- Twilio credential: TG_TWILIO (replacing TWC_TWILIO)
-- ============================================================================

-- 1. Workflow registry table
CREATE TABLE IF NOT EXISTS workflow_registry (
  id SERIAL PRIMARY KEY,
  workflow_number INT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  category TEXT NOT NULL,
  n8n_workflow_id TEXT,
  trigger_type TEXT NOT NULL DEFAULT 'cron',
  schedule TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  env_vars_required TEXT[] DEFAULT '{}',
  credentials_required TEXT[] DEFAULT '{}',
  supabase_tables TEXT[] DEFAULT '{}',
  depends_on INT[] DEFAULT '{}',
  last_run_at TIMESTAMPTZ,
  last_run_status TEXT,
  run_count INT DEFAULT 0,
  error_count INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Workflow run log
CREATE TABLE IF NOT EXISTS workflow_run_log (
  id BIGSERIAL PRIMARY KEY,
  workflow_number INT NOT NULL REFERENCES workflow_registry(workflow_number),
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  finished_at TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'running',
  items_processed INT DEFAULT 0,
  error_message TEXT,
  execution_id TEXT
);

-- 3. Seed all 150 workflows
INSERT INTO workflow_registry (workflow_number, name, description, category, trigger_type, schedule, env_vars_required, credentials_required, supabase_tables)
VALUES
  -- LEAD CAPTURE (01-05)
  (1, 'Website Lead Capture', 'Captures leads from website contact form webhook', 'lead_capture', 'webhook', NULL,
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY","TWILIO_PHONE"}',
    '{"TG_TWILIO"}',
    '{"leads"}'),
  (2, 'LSA Lead Capture', 'Parses Google Local Service Ads emails from Gmail', 'lead_capture', 'cron', '*/5 * * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{"Gmail OAuth"}',
    '{"leads"}'),
  (3, 'Phone Lead Capture', 'Captures inbound phone leads via Twilio webhook', 'lead_capture', 'webhook', NULL,
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{"TG_TWILIO"}',
    '{"leads"}'),
  (4, 'Facebook Lead Capture', 'Pulls leads from Facebook Lead Ads API', 'lead_capture', 'cron', '*/10 * * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","FB_PAGE_ACCESS_TOKEN"}',
    '{}',
    '{"leads"}'),
  (5, 'Manual Lead Entry', 'Processes manually entered leads from admin webhook', 'lead_capture', 'webhook', NULL,
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"leads"}'),

  -- JOBBER INTEGRATION (06-07)
  (6, 'Jobber Lead Sync', 'Syncs new leads to Jobber as customers', 'jobber_integration', 'cron', '*/5 * * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","JOBBER_API_KEY"}',
    '{}',
    '{"leads"}'),
  (7, 'Jobber Job Webhook', 'Receives job completion webhooks from Jobber', 'jobber_integration', 'webhook', NULL,
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","JOBBER_WEBHOOK_SECRET"}',
    '{}',
    '{"leads"}'),

  -- NURTURE SEQUENCES (08-18)
  (8, 'Welcome Series', '5-email welcome sequence for new leads', 'nurture', 'cron', '0 9 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"leads","nurture_sequences"}'),
  (9, 'Follow-Up Sequence', '3-touch follow-up: email, SMS, discount', 'nurture', 'cron', '0 10 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{"TG_TWILIO"}',
    '{"leads","nurture_sequences"}'),
  (10, 'Cross-Sell Nurture', 'Service-specific cross-sell with 30d cooldown', 'nurture', 'cron', '0 11 * * 1',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"leads"}'),
  (11, 'Re-Engagement Ladder', '5-stage re-engagement for inactive customers', 'nurture', 'cron', '0 9 * * 1',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"leads"}'),
  (12, 'VIP Upgrade', 'Upgrades customers to VIP after 3rd service', 'nurture', 'cron', '0 10 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"leads"}'),
  (13, 'Anniversary Campaign', 'Customer anniversary tiered discount emails', 'nurture', 'cron', '0 8 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"leads"}'),
  (14, 'Bundle Upsell', 'Bundle upsell offers at quote stage', 'nurture', 'cron', '0 11 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"leads"}'),
  (15, 'Seasonal Nurture - Spring', 'Spring season marketing push (aeration, cleanup)', 'nurture', 'cron', '0 9 * * 1',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"leads"}'),
  (16, 'Seasonal Nurture - Fall', 'Fall season marketing push (cleanup, leaf removal)', 'nurture', 'cron', '0 9 * * 1',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"leads"}'),
  (17, 'Seasonal Nurture - Commercial', 'Commercial season outreach', 'nurture', 'cron', '0 9 * * 1',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"leads"}'),
  (18, 'Weather Trigger Marketing', 'Weather-based marketing with 6 trigger types', 'nurture', 'cron', '0 7 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY","OPENWEATHER_API_KEY"}',
    '{"TG_TWILIO"}',
    '{"leads","weather_triggers"}'),

  -- SEO BOT (19-27)
  (19, 'Citation Submitter', 'Submits NAP to 19 business directories', 'seo', 'cron', '0 6 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"citations"}'),
  (20, 'HARO Pitcher', 'Monitors HARO for relevant journalist queries', 'seo', 'cron', '0 */6 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","ANTHROPIC_API_KEY"}',
    '{}',
    '{"haro_pitches"}'),
  (21, 'Guest Post Prospector', 'Finds guest post opportunities by DA', 'seo', 'cron', '0 5 * * 1',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"guest_post_prospects"}'),
  (22, 'Backlink Health Monitor', 'Checks backlink health and competitor links', 'seo', 'cron', '0 4 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"backlinks"}'),
  (23, 'Brand Mention Monitor', 'Detects unlinked brand mentions', 'seo', 'cron', '0 8 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"brand_mentions"}'),
  (24, 'Local News Scanner', 'Scans RSS feeds for local news opportunities', 'seo', 'cron', '0 */6 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"local_news_items"}'),
  (25, 'PR Auto-Scheduler', 'Schedules press releases from calendar', 'seo', 'cron', '0 7 * * 1',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"pr_releases"}'),
  (26, 'NAP Consistency Auditor', 'Audits NAP across all directories', 'seo', 'cron', '0 3 * * 0',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"citations"}'),
  (27, 'Weekly SEO Report', 'Compiles weekly SEO metrics report', 'seo', 'cron', '0 8 * * 1',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"citations","backlinks","haro_pitches","guest_post_prospects"}'),

  -- REVIEW & REPUTATION (28-30)
  (28, 'Review Request Sender', 'Sends review requests 2hrs after job completion', 'reviews', 'cron', '0 * * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{"TG_TWILIO"}',
    '{"leads","reviews"}'),
  (29, 'Google Review Sync', 'Daily sync of Google reviews with attribution', 'reviews', 'cron', '0 6 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","GOOGLE_PLACES_API_KEY"}',
    '{}',
    '{"reviews"}'),
  (30, 'Review Re-Engagement', 'Re-engages non-reviewers with 90d cooldown', 'reviews', 'cron', '0 10 * * 2',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"leads","reviews"}'),

  -- NEIGHBOR & FIELD (31, 51-56)
  (31, 'Neighbor Postcard Sender', 'Geocoded postcards mailed after job completion', 'field_marketing', 'cron', '0 12 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","LOB_API_KEY"}',
    '{}',
    '{"leads","neighbor_postcards"}'),
  (51, 'Field Marketing Task Creator', 'Creates yard sign/hanger tasks on job completion', 'field_marketing', 'webhook', NULL,
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"field_marketing_tasks"}'),
  (52, 'Field Marketing Escalation', '24/48/72hr escalation for incomplete tasks', 'field_marketing', 'cron', '0 8 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{"TG_TWILIO"}',
    '{"field_marketing_tasks"}'),
  (53, 'Yard Sign Tracker', 'GPS and condition tracking for deployed signs', 'field_marketing', 'webhook', NULL,
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"yard_signs"}'),
  (54, 'Door Hanger Batch Manager', 'Manages door hanger batch printing and distribution', 'field_marketing', 'cron', '0 7 * * 1',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"door_hanger_batches"}'),
  (55, 'Compliance Scorer', 'Daily field marketing compliance scoring (A-F)', 'field_marketing', 'cron', '0 18 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"field_marketing_tasks","compliance_scores"}'),
  (56, 'Weekly Field Report', 'Weekly field marketing execution report', 'field_marketing', 'cron', '0 8 * * 1',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"field_marketing_tasks","compliance_scores"}'),

  -- REFERRAL & PARTNER (32-33)
  (32, 'Referral Tracker', 'Tracks referral clicks, shares, and conversions', 'referral', 'webhook', NULL,
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"referral_links","referral_conversions"}'),
  (33, 'Partner Outreach', 'Automated realtor/partner outreach sequences', 'referral', 'cron', '0 10 * * 2,4',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"partners","partner_outreach"}'),

  -- COLD OUTREACH (34-35)
  (34, 'Commercial Cold Outreach', 'Cold email sequences for commercial properties', 'outreach', 'cron', '0 9 * * 1,3,5',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"commercial_prospects"}'),
  (35, 'Realtor Outreach', 'Partnership outreach to local realtors', 'outreach', 'cron', '0 10 * * 2,4',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"partners"}'),

  -- AI VOICE (36-37)
  (36, 'AI Voice Quote Processor', 'Processes AI voice quotes from Sameday', 'ai_voice', 'webhook', NULL,
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","SAMEDAY_API_KEY"}',
    '{}',
    '{"ai_quotes","ai_appointments"}'),
  (37, 'AI Appointment Sync', 'Syncs AI-booked appointments to Jobber', 'ai_voice', 'cron', '*/5 * * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","JOBBER_API_KEY"}',
    '{}',
    '{"ai_appointments"}'),

  -- ATTRIBUTION & OPTIMIZATION (38-50)
  (38, 'Lead-to-Job Attribution', 'Matches leads to completed jobs for attribution', 'optimization', 'cron', '0 2 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"leads","attribution_events"}'),
  (39, 'Email Engagement Scorer', 'Scores email engagement and updates lead data', 'optimization', 'cron', '0 3 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"leads","email_engagement"}'),
  (40, 'AB Test Auto-Optimizer', 'Detects winners with z-score significance', 'optimization', 'cron', '0 4 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"ab_tests","ab_variants"}'),
  (41, 'Lead Score Calibrator', 'Calibrates lead scoring weights from outcomes', 'optimization', 'cron', '0 2 * * 0',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"leads"}'),
  (42, 'Cross-Sell Bundle Optimizer', 'Optimizes cross-sell bundle recommendations', 'optimization', 'cron', '0 3 * * 0',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"leads"}'),
  (43, 'Weather Attribution', 'Attributes revenue to weather trigger campaigns', 'optimization', 'cron', '0 5 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"leads","weather_triggers"}'),
  (44, 'Backlink Strategy Optimizer', 'Optimizes backlink outreach based on results', 'optimization', 'cron', '0 4 * * 0',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"backlinks"}'),
  (45, 'Email Template Performance', 'Tracks and ranks email template performance', 'optimization', 'cron', '0 5 * * 1',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"email_engagement"}'),
  (46, 'Postcard ROI Tracker', 'Tracks ROI per postcard campaign', 'optimization', 'cron', '0 6 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"neighbor_postcards"}'),
  (47, 'Source Quality Ranker', 'Ranks lead sources by quality and conversion', 'optimization', 'cron', '0 3 * * 1',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"leads"}'),
  (48, 'Nurture Sequence Optimizer', 'Optimizes nurture sequence timing and content', 'optimization', 'cron', '0 4 * * 1',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"nurture_sequences"}'),
  (49, 'Lead Score Auto-Calibrator', 'Weekly auto-calibration of scoring weights', 'optimization', 'cron', '0 2 * * 0',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"leads"}'),
  (50, 'Revenue Channel Optimizer', 'Identifies highest-ROI marketing channels', 'optimization', 'cron', '0 5 * * 0',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"leads","attribution_events"}'),

  -- MARKETING CALENDAR (57-61)
  (57, 'Daily Marketing Briefing', '7am daily briefing of marketing activities', 'calendar', 'cron', '0 7 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{"TG_TWILIO"}',
    '{"marketing_calendar"}'),
  (58, 'Campaign Prep Reminder', '7-day and 3-day campaign prep reminders', 'calendar', 'cron', '0 8 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{"TG_TWILIO"}',
    '{"marketing_calendar"}'),
  (59, 'Inventory Alert', 'Alerts for low marketing material inventory', 'calendar', 'cron', '0 9 * * 1',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{"TG_TWILIO"}',
    '{"marketing_calendar"}'),
  (60, 'Yard Sign Collection Reminder', 'Reminds to collect deployed yard signs', 'calendar', 'cron', '0 16 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{"TG_TWILIO"}',
    '{"yard_signs"}'),
  (61, 'Seasonal Transition Alert', 'Alerts for season marketing transitions', 'calendar', 'cron', '0 8 1 * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"marketing_calendar"}'),

  -- PHASE 2 CORE (62-80)
  (62, 'Invoice Collections', 'Automated collections sequence for unpaid invoices', 'collections', 'cron', '0 9 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{"TG_TWILIO"}',
    '{"jobber_invoices","collection_attempts"}'),
  (63, 'Estimate Follow-Up', 'Follow-up sequence for open estimates', 'collections', 'cron', '0 10 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"jobber_estimates"}'),
  (64, 'Jobber Invoice & Estimate Sync', 'Syncs invoices and estimates from Jobber API', 'jobber_integration', 'cron', '0 */4 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","JOBBER_API_KEY"}',
    '{}',
    '{"jobber_invoices","jobber_estimates"}'),
  (65, 'Review-to-Referral Pipeline', 'Prompts good reviewers for referrals', 'reviews', 'cron', '0 10 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"reviews","referral_links"}'),
  (66, 'GBP Auto-Post', 'Auto-posts to Google Business Profile', 'social', 'cron', '0 10 * * 1,3,5',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","GOOGLE_MY_BUSINESS_API_KEY"}',
    '{}',
    '{"social_posts"}'),
  (67, 'Facebook Auto-Post', 'Auto-posts to Facebook business page', 'social', 'cron', '0 11 * * 2,4',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","FB_PAGE_ACCESS_TOKEN"}',
    '{}',
    '{"social_posts"}'),
  (68, 'LinkedIn Prospect Import', 'Imports prospects from LinkedIn search', 'linkedin', 'cron', '0 8 * * 1,3',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","APOLLO_API_KEY"}',
    '{}',
    '{"linkedin_prospects"}'),
  (69, 'LinkedIn Enrichment Pipeline', 'Enriches LinkedIn prospects with contact data', 'linkedin', 'cron', '0 9 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","APOLLO_API_KEY"}',
    '{}',
    '{"linkedin_prospects"}'),
  (70, 'LinkedIn Sequence Enrollment', 'Enrolls enriched prospects in outreach sequences', 'linkedin', 'cron', '0 10 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"linkedin_prospects","outreach_sequences"}'),
  (71, 'LinkedIn Outreach Sender', 'Sends LinkedIn outreach messages', 'linkedin', 'cron', '0 11 * * 1-5',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"linkedin_prospects","outreach_messages"}'),
  (72, 'Unscheduled Job Booking', 'Auto-contacts customers with unscheduled jobs', 'collections', 'cron', '0 10 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{"TG_TWILIO"}',
    '{"jobber_invoices"}'),
  (73, 'Seasonal Pre-Booking', 'Auto-rebooks last year customers for season', 'nurture', 'cron', '0 9 * * 1',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"leads"}'),
  (74, 'Customer Health Scoring', 'Calculates customer health scores', 'optimization', 'cron', '0 2 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"leads","customer_health_scores"}'),
  (75, 'High-Value Service Upsell', 'Targets customers for aeration, mulching, hardscaping', 'nurture', 'cron', '0 10 * * 2',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"leads"}'),
  (76, 'AI Review Response', 'AI-drafts Google review responses', 'reviews', 'cron', '0 9 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","ANTHROPIC_API_KEY","GOOGLE_MY_BUSINESS_API_KEY"}',
    '{}',
    '{"reviews","review_responses"}'),
  (77, 'Revenue Attribution Engine', 'Full revenue attribution pipeline', 'optimization', 'cron', '0 3 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"leads","jobber_invoices","attribution_events"}'),
  (78, 'Quote Follow-Up AI', 'AI-powered personalized quote follow-ups', 'collections', 'cron', '0 10 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","ANTHROPIC_API_KEY","BREVO_API_KEY"}',
    '{}',
    '{"jobber_estimates","quote_followup_log"}'),
  (79, 'Churn Intervention', 'Auto-intervention for at-risk customers', 'nurture', 'cron', '0 9 * * 1',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"leads","customer_health_scores"}'),
  (80, 'Weekly Owner Report', 'Comprehensive weekly metrics email to owner', 'reporting', 'cron', '0 7 * * 1',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"leads","jobber_invoices","reviews"}'),

  -- PHASE 2 CONTENT & SOCIAL (81-99)
  (81, 'AI Blog Generator', 'Claude-powered blog content pipeline', 'content', 'cron', '0 6 * * 1,4',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","ANTHROPIC_API_KEY"}',
    '{}',
    '{"blog_posts"}'),
  (82, 'Nextdoor Auto-Post', 'Auto-posts to Nextdoor business page', 'social', 'cron', '0 12 * * 2,5',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","NEXTDOOR_API_KEY"}',
    '{}',
    '{"social_posts"}'),
  (83, 'Subscription Outreach', 'Outreach for subscription plan signups', 'nurture', 'cron', '0 10 * * 3',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"leads","subscription_plans"}'),
  (84, 'Competitive Intelligence', 'Monitors competitor reviews and activity', 'optimization', 'cron', '0 5 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","GOOGLE_PLACES_API_KEY"}',
    '{}',
    '{"competitor_snapshots"}'),
  (85, 'Gift Certificate Fulfillment', 'Processes gift certificate purchases', 'nurture', 'webhook', NULL,
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"gift_certificates"}'),
  (86, 'Service Area Analysis', 'Analyzes demand density by ZIP code', 'optimization', 'cron', '0 3 * * 0',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"leads","service_area_metrics"}'),
  (87, 'Instagram Auto-Post', 'Auto-posts before/after photos to Instagram', 'social', 'cron', '0 14 * * 1,3,5',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","INSTAGRAM_ACCESS_TOKEN"}',
    '{}',
    '{"social_posts"}'),
  (88, 'Subscription Service Scheduler', 'Auto-schedules recurring subscription jobs', 'collections', 'cron', '0 8 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","JOBBER_API_KEY"}',
    '{}',
    '{"subscription_plans"}'),
  (89, 'Send Time Optimizer', 'Optimizes email send times per customer', 'optimization', 'cron', '0 2 * * 0',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"leads","send_time_preferences"}'),
  (90, 'Email Subject AB Tester', 'Auto-tests email subject line variants', 'optimization', 'cron', '0 3 * * 0',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"ab_tests"}'),
  (91, 'Commercial Account Manager', 'Manages multi-location commercial accounts', 'outreach', 'cron', '0 9 * * 1,3,5',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"commercial_accounts"}'),
  (92, 'Location SEO Generator', 'Generates location-specific SEO pages', 'seo', 'cron', '0 4 * * 0',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","ANTHROPIC_API_KEY"}',
    '{}',
    '{"location_seo_pages"}'),
  (93, 'Door Hanger Optimizer', 'Tests door hanger message variants', 'optimization', 'cron', '0 5 * * 0',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"door_hanger_batches"}'),
  (94, 'Winter Revenue Diversification', 'Pushes snow removal in off-season', 'nurture', 'cron', '0 9 * * 1',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"leads"}'),
  (95, 'Unified Dashboard Report', 'Compiles data for unified admin dashboard', 'reporting', 'cron', '0 */2 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"leads","reviews","jobber_invoices"}'),
  (96, 'Madison Lawn Score', 'Calculates neighborhood lawn health scores', 'optimization', 'cron', '0 3 * * 0',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"clean_scores","neighborhoods"}'),
  (97, 'Loyalty Points Engine', 'Processes loyalty point earning and redemption', 'nurture', 'webhook', NULL,
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"loyalty_accounts","loyalty_transactions"}'),
  (98, 'Service Anniversary Rebook', '12-month auto-rebook with pre-filled booking', 'nurture', 'cron', '0 9 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"leads"}'),
  (99, 'Multi-Service Progression', 'Tracks service adoption ladder upsells', 'nurture', 'cron', '0 10 * * 1',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"leads"}'),

  -- PHASE 2 COMPLIANCE & NPS (100-110)
  (100, 'SMS Consent Collector', 'Captures TCPA consent at every touchpoint', 'compliance', 'webhook', NULL,
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"sms_consent_log"}'),
  (101, 'NPS Survey Engine', 'Sends NPS surveys after service completion', 'reviews', 'cron', '0 10 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"nps_surveys"}'),
  (102, 'Review-to-Referral Pipeline V2', 'Enhanced review-to-referral with scoring', 'reviews', 'cron', '0 11 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"reviews","referral_links"}'),
  (103, 'Postcard Lead Scoring Bonus', 'Adds scoring bonus for postcard-sourced leads', 'optimization', 'cron', '0 4 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"leads","neighbor_postcards"}'),
  (104, 'Weather Calendar Integration', 'Syncs weather events to marketing calendar', 'calendar', 'cron', '0 6 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","OPENWEATHER_API_KEY"}',
    '{}',
    '{"marketing_calendar","weather_triggers"}'),
  (105, 'Brevo Auto-Segmentation', 'Auto-segments Brevo contacts from Supabase data', 'optimization', 'cron', '0 1 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"leads"}'),
  (106, 'Pricing Optimization Loop', 'Adjusts pricing based on acceptance rates', 'optimization', 'cron', '0 3 * * 0',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"ai_service_pricing","pricing_performance"}'),
  (107, 'Content Performance Loop', 'Tracks blog content leading to conversions', 'optimization', 'cron', '0 4 * * 1',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"blog_posts","leads"}'),
  (108, 'NPS Feedback Response', 'Auto-responds to NPS feedback by score', 'reviews', 'cron', '0 11 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"nps_surveys"}'),
  (109, 'Webhook Event Aggregator', 'Centralizes and deduplicates webhook events', 'optimization', 'webhook', NULL,
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"webhook_events"}'),
  (110, 'End-of-Day Reconciliation', 'Nightly data reconciliation and cleanup', 'reporting', 'cron', '0 23 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"leads","jobber_invoices"}'),

  -- PHASE 3 EXPANSION (111-150)
  (111, 'Automated Collections', 'Email+SMS collections for overdue invoices', 'collections', 'cron', '0 9 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{"TG_TWILIO"}',
    '{"jobber_invoices","collection_attempts"}'),
  (112, 'Open Estimate Follow-Up', 'AI-powered estimate follow-up sequences', 'collections', 'cron', '0 10 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","ANTHROPIC_API_KEY","BREVO_API_KEY"}',
    '{}',
    '{"jobber_estimates","quote_followup_log"}'),
  (113, 'Unscheduled Job Booker', 'Auto-contacts for unscheduled created jobs', 'collections', 'cron', '0 10 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{"TG_TWILIO"}',
    '{"jobber_invoices"}'),
  (114, 'Seasonal Pre-Booking Engine', 'Rebooking engine for past customers', 'nurture', 'cron', '0 9 * * 1',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"leads"}'),
  (115, 'GBP Auto-Posting V2', 'Enhanced Google Business Profile posting', 'social', 'cron', '0 10 * * 1,3,5',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","GOOGLE_MY_BUSINESS_API_KEY"}',
    '{}',
    '{"social_posts"}'),
  (116, 'Facebook Auto-Posting V2', 'Enhanced Facebook page posting', 'social', 'cron', '0 11 * * 2,4',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","FB_PAGE_ACCESS_TOKEN"}',
    '{}',
    '{"social_posts"}'),
  (117, 'Review Response AI', 'Claude-powered review response drafting', 'reviews', 'cron', '0 9 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","ANTHROPIC_API_KEY"}',
    '{}',
    '{"reviews","review_responses"}'),
  (118, 'Social Posting Scheduler', 'Cross-platform social media scheduler', 'social', 'cron', '0 8 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"social_posts"}'),
  (119, 'Quote Follow-Up AI V2', 'Enhanced AI quote follow-up with objection handling', 'collections', 'cron', '0 10 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","ANTHROPIC_API_KEY","BREVO_API_KEY"}',
    '{}',
    '{"jobber_estimates","quote_followup_log"}'),
  (120, 'Competitive Intelligence V2', 'Enhanced competitor monitoring with alerts', 'optimization', 'cron', '0 5 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","GOOGLE_PLACES_API_KEY"}',
    '{}',
    '{"competitor_snapshots"}'),
  (121, 'Gift Certificate Automation', 'Full gift cert purchase and redemption flow', 'nurture', 'webhook', NULL,
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"gift_certificates"}'),
  (122, 'Instagram Auto-Posting V2', 'Enhanced Instagram before/after posting', 'social', 'cron', '0 14 * * 1,3,5',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","INSTAGRAM_ACCESS_TOKEN"}',
    '{}',
    '{"social_posts"}'),
  (123, 'Nextdoor Auto-Posting V2', 'Enhanced Nextdoor community posting', 'social', 'cron', '0 12 * * 2,5',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","NEXTDOOR_API_KEY"}',
    '{}',
    '{"social_posts"}'),
  (124, 'Subscription Upsell Engine', 'Targeted subscription plan upsells', 'nurture', 'cron', '0 10 * * 3',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"leads","subscription_upsell_log"}'),
  (125, 'High-Value Service Upsell V2', 'Enhanced hardscaping and mulching upsells', 'nurture', 'cron', '0 10 * * 2',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"leads","service_upsell_log"}'),
  (126, 'Weekly Owner Report V2', 'Comprehensive weekly report with all metrics', 'reporting', 'cron', '0 7 * * 1',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"leads","jobber_invoices","reviews"}'),
  (127, 'AI Blog Content Pipeline', 'Full Claude-powered blog generation pipeline', 'content', 'cron', '0 6 * * 1,4',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","ANTHROPIC_API_KEY"}',
    '{}',
    '{"blog_posts"}'),
  (128, 'Scheduled Reminder Processor', 'Processes scheduled reminders and notifications', 'calendar', 'cron', '0 * * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{"TG_TWILIO"}',
    '{"scheduled_reminders"}'),
  (129, 'Seasonal Service Upsell', 'Seasonal service upsell campaign engine', 'nurture', 'cron', '0 9 * * 1',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"leads","seasonal_service_campaigns"}'),
  (130, 'Engagement Score Updater', 'Weekly customer engagement score calculation', 'optimization', 'cron', '0 2 * * 0',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"leads","engagement_scores"}'),
  (131, 'SMS Opt-In Collector V2', 'Enhanced TCPA consent collection', 'compliance', 'webhook', NULL,
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"sms_consent_log"}'),
  (132, 'Jobber Revenue Sync', 'Syncs Jobber invoice data for revenue tracking', 'jobber_integration', 'cron', '0 */4 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","JOBBER_API_KEY"}',
    '{}',
    '{"jobber_invoices"}'),
  (133, 'Review-Referral Bridge', 'Bridges review completion to referral prompts', 'reviews', 'cron', '0 10 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"reviews","referral_links","review_referral_bridge"}'),
  (134, 'LinkedIn Prospect Scraper', 'Scrapes LinkedIn for ideal prospects', 'linkedin', 'cron', '0 8 * * 1,3',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","APOLLO_API_KEY"}',
    '{}',
    '{"linkedin_prospects"}'),
  (135, 'LinkedIn Outreach Engine', 'Multi-touch LinkedIn outreach sequences', 'linkedin', 'cron', '0 10 * * 1-5',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"linkedin_prospects","outreach_messages"}'),
  (136, 'ResponsiBid Comparison Tester', 'Tests our pricing vs ResponsiBid for parity', 'optimization', 'cron', '0 4 * * 0',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"responsibid_test_results"}'),
  (137, 'Customer Winback Engine', 'Tiered winback for churned customers', 'nurture', 'cron', '0 9 * * 1',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"leads","winback_log"}'),
  (138, 'Service Area Analyzer', 'Analyzes demand by neighborhood/ZIP', 'optimization', 'cron', '0 3 * * 0',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"leads","service_area_metrics"}'),
  (139, 'SMS Consent Webhook', 'Webhook receiver for SMS consent events', 'compliance', 'webhook', NULL,
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"sms_consent_log"}'),
  (140, 'Pricing Auto-Calibrator', 'Auto-calibrates service pricing from market data', 'optimization', 'cron', '0 3 * * 0',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"ai_service_pricing","pricing_performance"}'),
  (141, 'Commercial Account Automator', 'Multi-location commercial account management', 'outreach', 'cron', '0 9 * * 1,3,5',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"commercial_accounts","commercial_outreach_log"}'),
  (142, 'Cross-Sell Intelligence', 'AI-powered cross-sell recommendations', 'nurture', 'cron', '0 10 * * 2',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"leads","cross_sell_log"}'),
  (143, 'Revenue Forecaster', 'Rolling 6-month revenue forecast', 'reporting', 'cron', '0 3 * * 0',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"leads","jobber_invoices","revenue_forecasts"}'),
  (144, 'Weather Damage Prevention Alerts', 'Proactive weather damage alert campaigns', 'nurture', 'cron', '0 7 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","OPENWEATHER_API_KEY","BREVO_API_KEY"}',
    '{"TG_TWILIO"}',
    '{"leads","weather_alert_log"}'),
  (145, 'Appointment Reminder Optimizer', 'Optimized appointment reminders via SMS/email', 'calendar', 'cron', '0 8 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{"TG_TWILIO"}',
    '{"leads"}'),
  (146, 'Customer Birthday Automator', 'Birthday discount email automation', 'nurture', 'cron', '0 8 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"leads"}'),
  (147, 'Daily KPI Digest', 'Morning KPI summary SMS to owner', 'reporting', 'cron', '0 7 * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{"TG_TWILIO"}',
    '{"leads","jobber_invoices","reviews"}'),
  (148, 'Stale Lead Reactivator', 'Tiered reactivation for stale leads', 'nurture', 'cron', '0 10 * * 1',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","BREVO_API_KEY"}',
    '{}',
    '{"leads","lead_reactivation_log"}'),
  (149, 'Google Analytics Reporter', 'Weekly GA4 metrics report', 'reporting', 'cron', '0 6 * * 1',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY","GA4_PROPERTY_ID","GOOGLE_SERVICE_ACCOUNT_KEY"}',
    '{}',
    '{"ga_reports"}'),
  (150, 'System Health Monitor', 'Monitors all system components health', 'reporting', 'cron', '*/30 * * * *',
    '{"SUPABASE_URL","SUPABASE_SERVICE_KEY"}',
    '{}',
    '{"system_health_log"}')
ON CONFLICT (workflow_number) DO NOTHING;

-- 4. Workflow status view for dashboard
CREATE OR REPLACE VIEW workflow_status_overview AS
SELECT
  category,
  COUNT(*) as total_workflows,
  COUNT(*) FILTER (WHERE status = 'active') as active,
  COUNT(*) FILTER (WHERE status = 'inactive') as inactive,
  COUNT(*) FILTER (WHERE status = 'error') as errored,
  COUNT(*) FILTER (WHERE last_run_status = 'success') as last_run_ok,
  COUNT(*) FILTER (WHERE last_run_status = 'error') as last_run_failed,
  MAX(last_run_at) as most_recent_run
FROM workflow_registry
GROUP BY category
ORDER BY category;

-- 5. Environment variable requirements view
CREATE OR REPLACE VIEW env_var_requirements AS
SELECT DISTINCT unnest(env_vars_required) as env_var,
  array_agg(DISTINCT workflow_number ORDER BY workflow_number) as used_by_workflows,
  COUNT(DISTINCT workflow_number) as workflow_count
FROM workflow_registry
GROUP BY 1
ORDER BY workflow_count DESC;

-- 6. RLS
ALTER TABLE workflow_registry ENABLE ROW LEVEL SECURITY;
ALTER TABLE workflow_run_log ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'workflow_registry' AND policyname = 'Service role full access') THEN
    CREATE POLICY "Service role full access" ON workflow_registry FOR ALL USING (auth.role() = 'service_role');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'workflow_run_log' AND policyname = 'Service role full access') THEN
    CREATE POLICY "Service role full access" ON workflow_run_log FOR ALL USING (auth.role() = 'service_role');
  END IF;
END $$;

-- 7. Indexes
CREATE INDEX IF NOT EXISTS idx_workflow_registry_category ON workflow_registry(category);
CREATE INDEX IF NOT EXISTS idx_workflow_registry_status ON workflow_registry(status);
CREATE INDEX IF NOT EXISTS idx_workflow_run_log_wf ON workflow_run_log(workflow_number);
CREATE INDEX IF NOT EXISTS idx_workflow_run_log_started ON workflow_run_log(started_at);
